export default {
  item_chat: require('../assets/cloud.png'),
  notification: require('../assets/notifications.png'),
  item_chat1: require('../assets/chat_item1.jpg'),
  item_chat2: require('../assets/chat_item2.jpg'),
  item_chat3: require('../assets/chat_item3.jpg'),
  item_chat4: require('../assets/chat_item4.jpg'),
  item_friend: require('../assets/friend_item1.jpg'),
  phone: require('../assets/phone.png'),
  video: require('../assets/video.png'),
  addfriend: require('../assets/friend.png'),
  listfriend: require('../assets/list.png'),
  group: require('../assets/group.png'),
  celendar: require('../assets/calendar.png'),
  clock: require('../assets/clock.png'),
  nosignal: require('../assets/no-signal.png'),
  post: require('../assets/post.png'),
  sort: require('../assets/sort.png'),
};
